# Generated by Django 3.0.5 on 2020-04-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_number', models.CharField(max_length=50)),
                ('car_intime', models.TimeField()),
                ('car_outtime', models.TimeField()),
                ('car_date', models.DateTimeField()),
            ],
        ),
    ]
