# Generated by Django 3.0.5 on 2020-04-16 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_details', '0003_parking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_id',
            new_name='id',
        ),
    ]
